serverAddr = "course.prafdin.ru"
serverPort = 7000
auth.method = "token"
auth.token = "devops"

[[proxies]]
name = "hook-baimukashev"
type = "http"
localPort = 8080
customDomains = ["webhook.baimukashev.course.prafdin.ru"]

[[proxies]]
name = "app-baimukashev"
type = "http"
localPort = 8181
customDomains = ["app.baimukashev.course.prafdin.ru"]

[[proxies]]
name = "ssh-baimukashev"
type = "tcp"
localPort = 22
remotePort = 3200
