name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          port: 3200
          username: kali
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            # Просто запускаем наш скрипт деплоя на стороне Kali Linux
            chmod +x /home/kali/catty-reminders-app/scripts/deploy.sh
            /home/kali/catty-reminders-app/scripts/deploy.sh
